[package]
name = "malloc"
version = "0.0.0"
authors = ["Richard <Richard>"]
edition = "2018"
license = "MIT"
description = "A malloc implementation for a web assembly module to expose"

[dependencies]
